import { useState } from 'react';
import styles from './Transactions.module.css';
import Spinner from './Spinner';

interface Transaction {
  id: number;
  type: string;
  date: string;
  amount: number;
  folio_type: string;
  investor: string;
  worker: string;
  action_type: string;
  link_id: number;
}

interface InvestorAddExpenseFormProps {
  onClose: () => void;
  onSave: (transaction: Transaction) => void;
}

interface FormData {
  amount: string;
  date: string;
  investor: string;
}

const InvestorAddExpenseForm: React.FC<InvestorAddExpenseFormProps> = ({ onClose, onSave }) => {
  const [formData, setFormData] = useState<FormData>({
    amount: '',
    date: '',
    investor: ''
  });
  const [isSaving, setIsSaving] = useState(false); // Add local saving state

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSaving) return; // Prevent multiple submissions

    setIsSaving(true); // Set saving state to true when starting submission

    try {
      const newTransaction: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'Investor Expense',
        date: formData.date,
        amount: parseFloat(formData.amount),
        folio_type: '',
        investor: formData.investor,
        worker: '',
        action_type: 'expense',
        link_id: 0 // Will be auto-generated by the server
      };

      const response = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: newTransaction.type,
          date: newTransaction.date,
          amount: newTransaction.amount,
          folio_type: newTransaction.folio_type,
          investor: newTransaction.investor,
          worker: newTransaction.worker,
          action_type: newTransaction.action_type,
          link_id: newTransaction.link_id
        }),
      });

      if (response.ok) {
        const result = await response.json();
        onSave(result.transaction);
        setFormData({ amount: '', date: '', investor: '' });
      } else {
        console.error('Failed to save transaction');
      }
    } catch (error) {
      console.error('Error saving transaction:', error);
    } finally {
      setIsSaving(false); // Set saving state to false when done
    }
  };

  return (
    <div className={styles.modalOverlay}>
      <div className={styles.modalContent}>
        <h2 className={styles.modalHeader}>Investor Add Expense</h2>
        <form onSubmit={handleSubmit}>
          <div className={styles.formGroup}>
            <label className={styles.formLabel}>Amount</label>
            <input 
              type="number" 
              name="amount"
              value={formData.amount}
              onChange={handleChange}
              className={styles.formInput}
              placeholder="Enter amount"
              required
            />
          </div>
          <div className={styles.formGroup}>
            <label className={styles.formLabel}>Date</label>
            <input 
              type="date" 
              name="date"
              value={formData.date}
              onChange={handleChange}
              className={styles.formInput}
              required
            />
          </div>
          <div className={styles.formGroup}>
            <label className={styles.formLabel}>Investor</label>
            <select 
              name="investor"
              value={formData.investor}
              onChange={handleChange}
              className={styles.formSelect}
              required
            >
              <option value="">Select Investor</option>
              <option value="investor1">Investor 1</option>
              <option value="investor2">Investor 2</option>
              <option value="investor3">Investor 3</option>
            </select>
          </div>

          <div className={styles.buttonGroup}>
            <button 
              type="button"
              onClick={onClose}
              className={styles.cancelButton}
              disabled={isSaving}
            >
              Cancel
            </button>
            <button 
              type="submit"
              className={`${styles.saveButton} ${styles.buttonInvestorExpense}`}
              disabled={isSaving}
            >
              {isSaving ? (
                <span className={styles.flexCenter}>
                  <Spinner size="sm" className={styles.spinnerMarginRight} />
                  Saving...
                </span>
              ) : (
                'Save'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default InvestorAddExpenseForm;