import { useState } from 'react';
import styles from './Transactions.module.css';
import Spinner from './Spinner';

interface Transaction {
  id: number;
  type: string;
  date: string | null;
  amount: number | null;
  folio_type: string | null;
  investor: string | null;
  worker: string | null;
  action_type: string | null;
  link_id: number | null;
}

interface WorkerAddExpenseFormProps {
  onClose: () => void;
  onSave: (transactions: Transaction[]) => void;
}

interface FormData {
  worker: string;
  date: string;
  amount: string;
  action_type: string;
}

const WorkerAddExpenseForm: React.FC<WorkerAddExpenseFormProps> = ({ onClose, onSave }) => {
  // Set default date to today
  const today = new Date().toISOString().split('T')[0];

  const [formData, setFormData] = useState<FormData>({
    worker: '',
    date: today,
    amount: '',
    action_type: ''
  });
  const [isSaving, setIsSaving] = useState(false); // Add local saving state

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSaving) return; // Prevent multiple submissions

    setIsSaving(true); // Set saving state to true when starting submission

    try {
      // Create 2 transactions for Worker Add Expense:
      // 1. Worker Folio Debit Entry (direct entry)
      // 2. Expense Folio Credit Entry (linked to worker debit)

      // 1. Worker Folio Debit Entry
      const workerDebit: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'debit',
        date: formData.date,
        amount: parseFloat(formData.amount),
        folio_type: 'worker',
        investor: null,
        worker: formData.worker,
        action_type: null,
        link_id: null // No link for this entry
      };

      // 2. Expense Folio Credit Entry (linked to worker debit)
      const expenseCredit: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'credit',
        date: null, // Empty since linked to worker debit
        amount: null, // Empty since linked to worker debit
        folio_type: 'expense',
        investor: null, // Empty since linked to worker debit
        worker: null,
        action_type: formData.action_type, // Action type from form
        link_id: 0 // Will be updated after worker debit is saved
      };

      // Save transactions in sequence to properly set link IDs
      const results = [];

      // Save first transaction (worker debit)
      const response1 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: workerDebit.type,
          date: workerDebit.date,
          amount: workerDebit.amount,
          folio_type: workerDebit.folio_type,
          investor: workerDebit.investor,
          worker: workerDebit.worker,
          action_type: workerDebit.action_type,
          link_id: workerDebit.link_id
        }),
      });

      if (!response1.ok) {
        console.error('Failed to save worker debit transaction');
        return;
      }
      const result1 = await response1.json();
      results.push(result1.transaction);

      // Now save second transaction (expense credit) with the link_id pointing to the worker debit transaction
      const response2 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: expenseCredit.type,
          date: expenseCredit.date,
          amount: expenseCredit.amount,
          folio_type: expenseCredit.folio_type,
          investor: expenseCredit.investor,
          worker: expenseCredit.worker,
          action_type: expenseCredit.action_type,
          link_id: result1.transaction.id // Link to the worker debit transaction (result1)
        }),
      });

      if (!response2.ok) {
        console.error('Failed to save expense credit transaction');
        return;
      }
      const result2 = await response2.json();
      results.push(result2.transaction);

      onSave(results);
      setFormData({ worker: '', date: today, amount: '', action_type: '' });
    } catch (error) {
      console.error('Error saving transactions:', error);
    } finally {
      setIsSaving(false); // Set saving state to false when done
    }
  };

  return (
    <div className={styles.modalOverlay}>
      <div className={styles.modalContent}>
        <h2 className={styles.modalHeader}>Worker Add Expense</h2>
        <form onSubmit={handleSubmit}>
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Worker</label>
              <select
                name="worker"
                value={formData.worker}
                onChange={handleChange}
                className={styles.formSelect}
                required
              >
                <option value="">Select Worker</option>
                <option value="Aarsh">Aarsh</option>
                <option value="Ramappan">Ramappan</option>
              </select>
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Date</label>
              <input
                type="date"
                name="date"
                value={formData.date}
                onChange={handleChange}
                className={styles.formInput}
                required
              />
            </div>
          </div>
          
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Amount</label>
              <input
                type="number"
                name="amount"
                value={formData.amount}
                onChange={handleChange}
                className={styles.formInput}
                placeholder="Enter amount"
                required
              />
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Action Type</label>
              <select
                name="action_type"
                value={formData.action_type}
                onChange={handleChange}
                className={styles.formSelect}
                required
              >
                <option value="">Select Action Type</option>
                <option value="carpentry">Carpentry</option>
                <option value="electricity">Electricity</option>
                <option value="travel">Travel</option>
                <option value="maintenance">Maintenance</option>
                <option value="cleaning">Cleaning</option>
              </select>
            </div>
          </div>

          <div className={styles.buttonGroup}>
            <button
              type="button"
              onClick={onClose}
              className={styles.cancelButton}
              disabled={isSaving}
            >
              Cancel
            </button>
            <button
              type="submit"
              className={`${styles.saveButton} ${styles.buttonWorkerExpense}`}
              disabled={isSaving}
            >
              {isSaving ? (
                <span className={styles.flexCenter}>
                  <Spinner size="sm" className={styles.spinnerMarginRight} />
                  Saving...
                </span>
              ) : (
                'Save'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default WorkerAddExpenseForm;