import { useState } from 'react';
import styles from '../Transactions.module.css';
import Spinner from '../utils/Spinner';

interface Transaction {
  id: number;
  type: string;
  date: string | null;
  amount: number | null;
  folio_type: string | null;
  investor: string | null;
  worker: string | null;
  action_type: string | null;
  link_id: number | null;
}

interface AddBufferAmountFormProps {
  onClose: () => void;
  onSave: (transactions: Transaction[]) => void;
}

interface FormData {
  amount: string;
  date: string;
  investor: string;
  worker: string;
}

const AddBufferAmountForm: React.FC<AddBufferAmountFormProps> = ({ onClose, onSave }) => {
  // Set default date to today
  const today = new Date().toISOString().split('T')[0];
  
  const [formData, setFormData] = useState<FormData>({
    amount: '',
    date: today,
    investor: '',
    worker: ''
  });
  const [isSaving, setIsSaving] = useState(false); // Add local saving state

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSaving) return; // Prevent multiple submissions

    setIsSaving(true); // Set saving state to true when starting submission

    try {
      // Create 3 transactions as specified
      const investorCreditId = 0; // Will be auto-generated by the server
      const investorDebitId = 0; // Will be auto-generated by the server
      const workerCreditId = 0; // Will be auto-generated by the server
      
      // Investor Folio Credit Entry
      const transaction1: Transaction = {
        id: investorCreditId,
        type: 'credit', // Type column shows "credit"
        date: formData.date,
        amount: parseFloat(formData.amount),
        folio_type: 'investor',
        investor: formData.investor,
        worker: '', // Worker value should be empty for investor folio entries
        action_type: '', // Action Type column should be empty
        link_id: 0 // Will be auto-generated by the server or 0 if not linked
      };

      // Investor Folio Debit Entry
      const transaction2: Transaction = {
        id: investorDebitId,
        type: 'debit', // Type column shows "debit"
        date: formData.date,
        amount: parseFloat(formData.amount),
        folio_type: 'investor',
        investor: formData.investor,
        worker: '', // Worker value should be empty for investor folio entries
        action_type: '', // Action Type column should be empty
        link_id: 0 // Will be auto-generated by the server or 0 if not linked
      };

      // Worker Folio Credit Entry with link_id to investor debit - date and amount null since linked
      const transaction3: Transaction = {
        id: workerCreditId,
        type: 'credit', // Type column shows "credit"
        date: null, // Date should be null for linked transactions
        amount: null, // Amount should be null for linked transactions
        folio_type: 'worker',
        investor: null, // Investor should be null for linked transactions
        worker: formData.worker,
        action_type: null, // Action Type column should be null
        link_id: 2 // Will be updated after investor debit is saved
      };

      // Save all 3 transactions
      const transactionsToSave = [transaction1, transaction2, transaction3];
      
      // Save transactions in sequence to properly set link IDs
      const results = [];
      
      // Save first transaction (investor credit)
      let response1 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: transaction1.type,
          date: transaction1.date,
          amount: transaction1.amount,
          folio_type: transaction1.folio_type,
          investor: transaction1.investor,
          worker: transaction1.worker,
          action_type: transaction1.action_type,
          link_id: transaction1.link_id
        }),
      });
      
      if (!response1.ok) {
        console.error('Failed to save first transaction');
        return;
      }
      const result1 = await response1.json();
      results.push(result1.transaction);
      
      // Save second transaction (investor debit)
      let response2 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: transaction2.type,
          date: transaction2.date,
          amount: transaction2.amount,
          folio_type: transaction2.folio_type,
          investor: transaction2.investor,
          worker: transaction2.worker,
          action_type: transaction2.action_type,
          link_id: transaction2.link_id
        }),
      });
      
      if (!response2.ok) {
        console.error('Failed to save second transaction');
        return;
      }
      const result2 = await response2.json();
      results.push(result2.transaction);
      
      // Now save third transaction (worker credit) with the link_id pointing to the second transaction
      let response3 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: transaction3.type,
          date: transaction3.date,
          amount: transaction3.amount,
          folio_type: transaction3.folio_type,
          investor: transaction3.investor,
          worker: transaction3.worker,
          action_type: transaction3.action_type,
          link_id: result2.transaction.id // Link to the second transaction
        }),
      });
      
      if (!response3.ok) {
        console.error('Failed to save third transaction');
        return;
      }
      const result3 = await response3.json();
      results.push(result3.transaction);
      
      onSave(results);
      setFormData({ amount: '', date: '', investor: '', worker: '' });
    } catch (error) {
      console.error('Error saving transactions:', error);
    } finally {
      setIsSaving(false); // Set saving state to false when done
    }
  };

  return (
    <div className={styles.modalOverlay}>
      <div className={styles.modalContent}>
        <h2 className={styles.modalHeader}>Add Buffer Amount</h2>
        <form onSubmit={handleSubmit}>
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Investor</label>
              <select
                name="investor"
                value={formData.investor}
                onChange={handleChange}
                className={styles.formSelect}
                required
              >
                <option value="">Select Investor</option>
                <option value="Anup">Anup</option>
                <option value="Aneshwar">Aneshwar</option>
              </select>
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Worker</label>
              <select
                name="worker"
                value={formData.worker}
                onChange={handleChange}
                className={styles.formSelect}
                required
              >
                <option value="">Select Worker</option>
                <option value="Aarsh">Aarsh</option>
                <option value="Ramappan">Ramappan</option>
              </select>
            </div>
          </div>
          
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Date</label>
              <input
                type="date"
                name="date"
                value={formData.date}
                onChange={handleChange}
                className={styles.formInput}
                required
              />
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Amount</label>
              <input
                type="number"
                name="amount"
                value={formData.amount}
                onChange={handleChange}
                className={styles.formInput}
                placeholder="Enter amount"
                required
              />
            </div>
          </div>
          <div className={styles.buttonGroup}>
            <button 
              type="button"
              onClick={onClose}
              className={styles.cancelButton}
              disabled={isSaving}
            >
              Cancel
            </button>
            <button 
              type="submit"
              className={styles.saveButton}
              disabled={isSaving}
            >
              {isSaving ? (
                <span className={styles.flexCenter}>
                  <Spinner size="sm" className={styles.spinnerMarginRight} />
                  Saving...
                </span>
              ) : (
                'Save'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddBufferAmountForm;