import { useState } from 'react';
import styles from '../Transactions.module.css';
import Spinner from '../utils/Spinner';

interface Transaction {
  id: number;
  type: string;
  date: string | null;
  amount: number | null;
  folio_type: string | null;
  investor: string | null;
  worker: string | null;
  action_type: string | null;
  link_id: number | null;
}

interface InvestorAddExpenseFormProps {
  onClose: () => void;
  onSave: (transactions: Transaction[]) => void;
}

interface FormData {
  investor: string;
  date: string;
  amount: string;
  action_type: string;
}

const InvestorAddExpenseForm: React.FC<InvestorAddExpenseFormProps> = ({ onClose, onSave }) => {
  // Set default date to today
  const today = new Date().toISOString().split('T')[0];

  const [formData, setFormData] = useState<FormData>({
    investor: '',
    date: today,
    amount: '',
    action_type: ''
  });
  const [isSaving, setIsSaving] = useState(false); // Add local saving state

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSaving) return; // Prevent multiple submissions

    setIsSaving(true); // Set saving state to true when starting submission

    try {
      // Create 3 transactions for Investor Add Expense:
      // 1. Investor Folio Credit Entry (direct entry)
      // 2. Investor Folio Debit Entry (direct entry) 
      // 3. Expense Folio Credit Entry (linked to investor debit)

      // 1. Investor Folio Credit Entry
      const investorCredit: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'credit',
        date: formData.date,
        amount: parseFloat(formData.amount),
        folio_type: 'investor',
        investor: formData.investor,
        worker: null,
        action_type: null,
        link_id: null // No link for this entry
      };

      // 2. Investor Folio Debit Entry  
      const investorDebit: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'debit',
        date: formData.date,
        amount: parseFloat(formData.amount),
        folio_type: 'investor',
        investor: formData.investor,
        worker: null,
        action_type: null,
        link_id: null // No link for this entry
      };

      // 3. Expense Folio Credit Entry (linked to investor debit)  
      const expenseCredit: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'credit',
        date: null, // Empty since linked to investor debit
        amount: null, // Empty since linked to investor debit
        folio_type: 'expense',
        investor: null, // Empty since linked to investor debit
        worker: null,
        action_type: formData.action_type, // Action type from form
        link_id: 0 // Will be updated after investor debit is saved
      };

      // Save transactions in sequence to properly set link IDs
      const results = [];

      // Save first transaction (investor credit)
      const response1 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: investorCredit.type,
          date: investorCredit.date,
          amount: investorCredit.amount,
          folio_type: investorCredit.folio_type,
          investor: investorCredit.investor,
          worker: investorCredit.worker,
          action_type: investorCredit.action_type,
          link_id: investorCredit.link_id
        }),
      });

      if (!response1.ok) {
        console.error('Failed to save investor credit transaction');
        return;
      }
      const result1 = await response1.json();
      results.push(result1.transaction);

      // Save second transaction (investor debit)
      const response2 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: investorDebit.type,
          date: investorDebit.date,
          amount: investorDebit.amount,
          folio_type: investorDebit.folio_type,
          investor: investorDebit.investor,
          worker: investorDebit.worker,
          action_type: investorDebit.action_type,
          link_id: investorDebit.link_id
        }),
      });

      if (!response2.ok) {
        console.error('Failed to save investor debit transaction');
        return;
      }
      const result2 = await response2.json();
      results.push(result2.transaction);

      // Now save third transaction (expense credit) with the link_id pointing to the investor debit transaction
      const response3 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: expenseCredit.type,
          date: expenseCredit.date,
          amount: expenseCredit.amount,
          folio_type: expenseCredit.folio_type,
          investor: expenseCredit.investor,
          worker: expenseCredit.worker,
          action_type: expenseCredit.action_type,
          link_id: result2.transaction.id // Link to the investor debit transaction (result2)
        }),
      });

      if (!response3.ok) {
        console.error('Failed to save expense credit transaction');
        return;
      }
      const result3 = await response3.json();
      results.push(result3.transaction);

      onSave(results);
      setFormData({ investor: '', date: today, amount: '', action_type: '' });
    } catch (error) {
      console.error('Error saving transactions:', error);
    } finally {
      setIsSaving(false); // Set saving state to false when done
    }
  };

  return (
    <div className={styles.modalOverlay}>
      <div className={styles.modalContent}>
        <h2 className={styles.modalHeader}>Investor Add Expense</h2>
        <form onSubmit={handleSubmit}>
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Investor</label>
              <select
                name="investor"
                value={formData.investor}
                onChange={handleChange}
                className={styles.formSelect}
                required
              >
                <option value="">Select Investor</option>
                <option value="Anup">Anup</option>
                <option value="Aneshwar">Aneshwar</option>
              </select>
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Date</label>
              <input
                type="date"
                name="date"
                value={formData.date}
                onChange={handleChange}
                className={styles.formInput}
                required
              />
            </div>
          </div>
          
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Amount</label>
              <input
                type="number"
                name="amount"
                value={formData.amount}
                onChange={handleChange}
                className={styles.formInput}
                placeholder="Enter amount"
                required
              />
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Action Type</label>
              <select
                name="action_type"
                value={formData.action_type}
                onChange={handleChange}
                className={styles.formSelect}
                required
              >
                <option value="">Select Action Type</option>
                <option value="carpentry">Carpentry</option>
                <option value="electricity">Electricity</option>
                <option value="travel">Travel</option>
                <option value="maintenance">Maintenance</option>
                <option value="cleaning">Cleaning</option>
              </select>
            </div>
          </div>

          <div className={styles.buttonGroup}>
            <button
              type="button"
              onClick={onClose}
              className={styles.cancelButton}
              disabled={isSaving}
            >
              Cancel
            </button>
            <button
              type="submit"
              className={`${styles.saveButton} ${styles.buttonInvestorExpense}`}
              disabled={isSaving}
            >
              {isSaving ? (
                <span className={styles.flexCenter}>
                  <Spinner size="sm" className={styles.spinnerMarginRight} />
                  Saving...
                </span>
              ) : (
                'Save'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default InvestorAddExpenseForm;