import { useState } from 'react';
import styles from '../Transactions.module.css';
import Spinner from '../utils/Spinner';

interface Transaction {
  id: number;
  type: string;
  date: string | null;
  amount: number | null;
  folio_type: string | null;
  investor: string | null;
  worker: string | null;
  action_type: string | null;
  link_id: number | null;
}

interface WorkerTransferFormProps {
  onClose: () => void;
  onSave: (transactions: Transaction[]) => void; // Now returns an array of transactions
}

interface FormData {
  amount: string;
  date: string;
  from_worker: string;
  to_worker: string;
}

const WorkerTransferForm: React.FC<WorkerTransferFormProps> = ({ onClose, onSave }) => {
  // Set default date to today
  const today = new Date().toISOString().split('T')[0];
  
  const [formData, setFormData] = useState<FormData>({
    amount: '',
    date: today,
    from_worker: '',
    to_worker: ''
  });
  const [isSaving, setIsSaving] = useState(false); // Add local saving state

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSaving) return; // Prevent multiple submissions

    setIsSaving(true); // Set saving state to true when starting submission

    try {
      // Create 2 transactions for the worker transfer
      // Debit entry (from)
      const debitTransaction: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'debit', // Type column shows "debit"
        date: formData.date, // Date filled for debit entry
        amount: parseFloat(formData.amount), // Amount filled for debit entry
        folio_type: 'worker', // Folio type is 'worker'
        investor: null, // Investor should be null for linked transactions
        worker: formData.from_worker, // Worker value for debit side
        action_type: null, // Action type should be null for debit in transfer
        link_id: 0 // Will be auto-generated by the server
      };

      // Credit entry (to) - linked to the debit entry
      const creditTransaction: Transaction = {
        id: 0, // Will be auto-generated by the server
        type: 'credit', // Type column shows "credit"
        date: null, // Date should be null for linked transactions
        amount: null, // Amount should be null for linked transactions
        folio_type: 'worker', // Folio type is 'worker'
        investor: null, // Investor should be null for linked transactions
        worker: formData.to_worker, // Worker value for credit side
        action_type: 'transfer', // Action type is transfer for credit in worker transfer
        link_id: 0 // Will be updated after debit is saved
      };

      // Save transactions in sequence to properly set link IDs
      const results = [];

      // Save first transaction (debit from)
      const response1 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: debitTransaction.type,
          date: debitTransaction.date,
          amount: debitTransaction.amount,
          folio_type: debitTransaction.folio_type,
          investor: debitTransaction.investor,
          worker: debitTransaction.worker,
          action_type: debitTransaction.action_type,
          link_id: debitTransaction.link_id
        }),
      });

      if (!response1.ok) {
        console.error('Failed to save debit transaction');
        return;
      }
      const result1 = await response1.json();
      results.push(result1.transaction);

      // Now save second transaction (credit to) with the link_id pointing to the first transaction
      const response2 = await fetch('/api/transactions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: creditTransaction.type,
          date: creditTransaction.date,
          amount: creditTransaction.amount,
          folio_type: creditTransaction.folio_type,
          investor: creditTransaction.investor,
          worker: creditTransaction.worker,
          action_type: creditTransaction.action_type,
          link_id: result1.transaction.id // Link to the first (debit) transaction
        }),
      });

      if (!response2.ok) {
        console.error('Failed to save credit transaction');
        return;
      }
      const result2 = await response2.json();
      results.push(result2.transaction);

      onSave(results);
      setFormData({ amount: '', date: today, from_worker: '', to_worker: '' });
    } catch (error) {
      console.error('Error saving transactions:', error);
    } finally {
      setIsSaving(false); // Set saving state to false when done
    }
  };

  return (
    <div className={styles.modalOverlay}>
      <div className={styles.modalContent}>
        <h2 className={styles.modalHeader}>Worker Transfer</h2>
        <form onSubmit={handleSubmit}>
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>From Worker</label>
              <select
                name="from_worker"
                value={formData.from_worker}
                onChange={handleChange}
                className={styles.formSelect}
                required
              >
                <option value="">Select From Worker</option>
                <option value="Aarsh">Aarsh</option>
                <option value="Ramappan">Ramappan</option>
              </select>
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>To Worker</label>
              <select
                name="to_worker"
                value={formData.to_worker}
                onChange={handleChange}
                className={styles.formSelect}
                required
                disabled={!formData.from_worker}
              >
                <option value="">Select To Worker</option>
                {formData.from_worker !== 'Aarsh' && <option value="Aarsh">Aarsh</option>}
                {formData.from_worker !== 'Ramappan' && <option value="Ramappan">Ramappan</option>}
              </select>
            </div>
          </div>
          
          <div className={styles.formRow}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Date</label>
              <input
                type="date"
                name="date"
                value={formData.date}
                onChange={handleChange}
                className={styles.formInput}
                required
              />
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Amount</label>
              <input
                type="number"
                name="amount"
                value={formData.amount}
                onChange={handleChange}
                className={styles.formInput}
                placeholder="Enter amount"
                required
              />
            </div>
          </div>

          <div className={styles.buttonGroup}>
            <button 
              type="button"
              onClick={onClose}
              className={styles.cancelButton}
              disabled={isSaving}
            >
              Cancel
            </button>
            <button 
              type="submit"
              className={`${styles.saveButton} ${styles.buttonWorkerTransfer}`}
              disabled={isSaving}
            >
              {isSaving ? (
                <span className={styles.flexCenter}>
                  <Spinner size="sm" className={styles.spinnerMarginRight} />
                  Saving...
                </span>
              ) : (
                'Save'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default WorkerTransferForm;